---
- name: Install RabbitMQ
  hosts: all
  become: yes

  tasks:
  - name: Add RabbitMQ repository
    apt_repository:
      repo: deb https://dl.bintray.com/rabbitmq/debian {{ ansible_distribution_release }} main
      state: present

  - name: Install RabbitMQ
    apt:
      name: rabbitmq-server
      state: latest

  - name: Start and enable RabbitMQ service
    service:
      name: rabbitmq-server
      state: started
      enabled: yes

  - name: Add RabbitMQ nodes to the cluster
    shell: rabbitmqctl stop_app; rabbitmqctl join_cluster rabbit@{{ inventory_hostname_short }}; rabbitmqctl start_app
    when: "'rabbit@{{ inventory_hostname_short }}' not in rabbitmqctl cluster_status.stdout"

  - name: Create HA policy
    shell: rabbitmqctl set_policy ha-all '^(?!amq\.).*' '{"ha-mode":"all"}'